name: cuvs_cagra
constraints:
  build: cuvs_bench.config.algos.constraints.cuvs_cagra_build
  search: cuvs_bench.config.algos.constraints.cuvs_cagra_search
groups:
  base:
    build:
      graph_degree: [64]
      intermediate_graph_degree: [96]
      graph_build_algo: ["NN_DESCENT"]
      vq_kmeans_trainset_fraction: [0.02, 0.04, 0.08, 0.1, 0.15, 0.2, 0.5]
      pq_kmeans_trainset_fraction: [0.02, 0.04, 0.08, 0.1, 0.15, 0.2, 0.5]
    search:
      itopk: [32]
      search_width: [2]
  test:
    build:
      graph_degree: [32]
      intermediate_graph_degree: [32]
      graph_build_algo: ["NN_DESCENT"]
    search:
      itopk: [32]
      search_width: [1, 2]
